name: Build and Push Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: tp1
          push: true
          tags: andys0804/tp1:latest

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd /home/${{ secrets.VM_USER }}/as
            IMAGE="andys0804/tp1:latest"
            CONTAINER_NAME="my_app"

            echo "Pulling latest image..."
            docker pull $IMAGE

            echo "Stopping old container..."
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            echo "Starting new container..."
            docker run -d --name $CONTAINER_NAME -p 5242:5242 $IMAGE

            echo "Deployment complete!"
